config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "home#index"
  resources :books, except: %i[index] do
    resources :feedbacks, except: %i[index new show]
  end
  resources :book_sellers
  resources :addresses, except: %i[show]
  get "cart", to: "carts#show"
  delete "clear_cart/:secret_id", to: "carts#destroy", as: "clear_cart"
  post "cart_item/add/:book_id", to: "cart_items#create", as: "cart_item_add"
  delete "cart_item/:id", to: "cart_items#destroy", as: "cart_item_delete"
  patch "cart_item/:id", to: "cart_items#update", as: "cart_item"
  resources :orders, except: %i[edit new]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in? && current_user.role == "customer"
      @books_seller = BookSeller.paginate(page: params[:page], per_page: 30).order(:created_at)
    elsif user_signed_in? && current_user.role == "seller"
      @orders = Order.joins(order_items: { book_seller: :user })
        .where(users: { id: current_user.id }).distinct
      @feedbacks = Feedback.all
    elsif user_signed_in? && current_user.role == "author"
      @books = Book.where(user_id: current_user.id).paginate(page: params[:page], per_page: 30).order(:created_at)
      @rating = Feedback.where(user_id: current_user.id).average(:rating).to_f.round(2)
    else
      @q = BookSeller.ransack(params[:q])
      @books_seller = @q.result(distinct: true).paginate(page: params[:page], per_page: 30).order(:created_at)
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_author.html.erb
<% @books.each do |book| %>
  <div class="card d-inline-flex justify-content-start flex-direction: row mx-3 mb-2 " style="width: 18rem;">
    <%= image_tag url_for(book.book_image) , class: "card-img-top p-1" , alt: "book-image" %>
    <div class="card-body">
      <h5 class="card-title d-flex justify-content-center"><%= book.book_name  %></h5>
      <p class="card-text d-flex justify-content-center mb-2 fs-5">₹<%= book.MRP %></p>
      <%= link_to "Show" , book_path(book) ,class: "btn btn-primary d-flex justify-content-center" %>
    </div>
  </div>
<% end %>
<div class="flickr_pagination d-flex justify-content-center mt-3">
  <%= will_paginate @books %>
</div>

app/views/home/_customer.html.erb
  <% @books_seller.each do |books_seller| %>
  <% if books_seller.quantity > 0 %>
    <%= link_to book_path(books_seller.book), class: "card-link text-decoration-none text-dark" do %>
      <div class="card d-inline-flex justify-content-start flex-direction: row mx-3 mb-2" style="width: 18rem;">
        <%= image_tag url_for(books_seller.book.book_image) , class: "card-img-top p-1" , alt: "book-image" %>
        <div class="card-body">
          <h5 class="card-title d-flex justify-content-center"><%= books_seller.book.book_name  %></h5>
          <p class="card-text d-flex justify-content-center"><strong><%= books_seller.book.user.name %></strong></p>
          <p class="card-text d-flex justify-content-center mb-2 fs-5">₹<%= books_seller.seller_price %></p>
          <%= link_to "Add to Bag" , cart_item_add_path(books_seller.book_id) , data: {turbo_method: "post"} , class: "btn btn-primary d-flex justify-content-center" , method: :post %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>
<div class="flickr_pagination d-flex justify-content-center mt-3">
  <%= will_paginate @books_seller %>
</div>

app/views/home/_seller.html.erb
  
<div id="chartsCarousel" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <p class="fs-4 fw-semibold text-center">Orders by Day of the Week</p>
      <%= line_chart @orders.group_by_day_of_week(:created_at, format: "%a").count, height: "400px", width: "100%" %>
    </div>
    <div class="carousel-item">
      <p class="fs-4 fw-semibold text-center">Orders by Month</p>
      <%= line_chart @orders.group_by_month(:created_at, format: "%b %Y", range: 1.year.ago..Time.now).count, height: "400px", width: "100%" %>
    </div>
    <div class="carousel-item">
      <p class="fs-4 fw-semibold text-center">Orders by Day of the Month</p>
      <%= column_chart @orders.group_by_day(:created_at, format: "%d %b", range: Time.current.beginning_of_month..Time.current).count, height: "400px", width: "100%" %>
    </div>
  </div>

  <!-- Dark Navigation Buttons -->
  <button class="carousel-control-prev btn btn-light" type="button" data-bs-target="#chartsCarousel" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next btn btn-light" type="button" data-bs-target="#chartsCarousel" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<div class="mt-4">
  <p class="fs-4 fw-semibold text-center">Average Book Ratings</p>
  <%= pie_chart @feedbacks.joins(:book).group("books.book_name").average(:rating), height: "400px", width: "100%" %>
</div>

app/views/home/index.html.erb
<% if !user_signed_in? || current_user.role == "customer"%>
  <%= render "customer" %>
<% end %>

<% if user_signed_in? && current_user.role == "author"%>
  <%= render "author" %>
<% end %>

<% if user_signed_in? && current_user.role == "seller" %>
  <%= render "seller" %>
<% end %>