config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "home#index"
  resources :books, except: %i[index] do
    resources :feedbacks, except: %i[index new show]
  end
  resources :book_sellers
  resources :addresses, except: %i[show]
  get "cart", to: "carts#show"
  delete "clear_cart/:secret_id", to: "carts#destroy", as: "clear_cart"
  post "cart_item/add/:book_id", to: "cart_items#create", as: "cart_item_add"
  delete "cart_item/:id", to: "cart_items#destroy", as: "cart_item_delete"
  patch "cart_item/:id", to: "cart_items#update", as: "cart_item"
  resources :orders, except: %i[edit new]
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_sellers, dependent: :destroy
  has_many :users, through: :book_sellers, dependent: :destroy
  has_one_attached :book_image, dependent: :destroy
  has_many :feedbacks, dependent: :destroy
  validates :book_name, presence: true, length: { in: 1..50 }
  validates :book_image, presence: true
  validates :MRP, presence: true, numericality: { greater_than: 0 }
  validates :pages, presence: true, numericality: { greater_than: 0 }
  validates :publisher_name, presence: true, length: { in: 1..50 }
  validates :publication_date, presence: true
  validates :language, presence: true, length: { in: 1..50 }
  validates :description, presence: true, length: { minimum: 10 }

  def self.ransackable_associations(auth_object = nil)
    ["book_image_attachment", "book_image_blob", "book_sellers", "user", "users"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["MRP", "book_name", "created_at", "description", "id", "language", "pages", "publication_date", "publisher_name", "updated_at", "user_id"]
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: %i[show]

  def new
    @book = Book.new
    @book.user_id = current_user.id
  end

  def create
    @book = Book.new(book_params)
    @book.user = current_user
    if @book.save
      flash[:notice] = "Book added successfully"
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @book = Book.find(params[:id])
    @book_seller = BookSeller.find_by(book_id: params[:id])
  end

  def edit
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.user != current_user
      flash[:alert] = "You are not authorized to edit this book"
      redirect_to root_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.user != current_user
      flash[:alert] = "You are not authorized to edit this book"
      redirect_to root_path
    elsif @book.update(book_params)
      flash[:notice] = "Book updated successfully"
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.user != current_user
      flash[:alert] = "You are not authorized to delete this book"
      redirect_to root_path
    else
      @book.destroy
      flash[:notice] = "Book deleted successfully"
      redirect_to root_path
    end
  end

  private

  def book_params
    params.require(:book).permit(:book_name, :book_image, :MRP, :pages, :publisher_name, :publication_date, :language, :description, :book_image)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
  <%= render "shared/error" , obj: @book %>
<%= form_with model: @book, local: true do |form| %>
  <div class="form-group mb-3">
    <%= form.label :book_name, "Book Name" , class: "form-label" %>
    <%= form.text_field :book_name , class: "form-control" , required:true %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :book_image , "Book Image" , class: "form-label" %>
    <%= form.file_field :book_image , class: "form-control" , required:@book.new_record? %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :MRP, "Maximum Retail Price (MRP)" ,class: "form-label"%>
    <%= form.number_field :MRP ,class: "form-control" , min: 1 , required:true %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :pages, "Number of Pages" , class: "form-label" %>
    <%= form.number_field :pages , class: "form-control" , min: 1 , required:true %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :publisher_name, "Publisher Name", class: "form-label" %>
    <%= form.text_field :publisher_name , class: "form-control" , required:true %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :publication_date, "Publication Date" , class: "form-label" %>
    <%= form.date_field :publication_date , class: "form-control" , required:true %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :language, "Language" , class: "form-label" %>
    <%= form.text_field :language , class: "form-control" , required:true %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :description, "Description", class: "form-label" %>
    <%= form.text_area :description, rows: 4, cols: 50 , class: "form-control" , required:true %>
  </div>

  <div class="form-group mb-3">
    <%= form.hidden_field :user_id, value: current_user.id, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.submit  class: "form-control btn btn-primary" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<% if user_signed_in? && current_user.role == "author" %>
  <%= link_to raw('<i class="fa-solid fa-arrow-left fa-xl"></i>'), book_path(@book) %>
  <h2 class="my-3">Edit Book</h2>

  <%= render "form" %>

<% end %>

app/views/books/new.html.erb
<% if user_signed_in? && current_user.role == "author" %>
  <%= link_to raw('<i class="fa-solid fa-arrow-left fa-xl"></i>'), root_path %>
  <h2 class="my-3">Add Book</h2>

  <%= render "form" %>

<% end %>

app/views/books/show.html.erb
<%= link_to raw('<i class="fa-solid fa-arrow-left fa-xl"></i>'), root_path, class: "d-flex justify-content-start mb-3" %>

<div class="container">
  <div class="row">
    <!-- Book Image -->
    <div class="col-md-4 text-center">
      <%= image_tag url_for(@book.book_image.representation(resize_to_limit: [305, 466])),
        class: "rounded shadow-sm mt-3", alt: "Book Image" %>
    </div>

    <!-- Book Details -->
    <div class="col-md-8">
      <h1 class="fw-bold"><%= @book.book_name %></h1>
      <p><strong>Author Name: </strong><%= @book.user.name %></p>

      <% if !user_signed_in? || current_user.role == "customer" %>
        <p><strong>Price: </strong>₹<%= @book_seller.seller_price %></p>
      <% else %>
        <p><strong>MRP: </strong>₹<%= @book.MRP %></p>
      <% end %>

      <p><strong>Pages: </strong><%= @book.pages %></p>
      <p><strong>Publication: </strong><%= @book.publisher_name %></p>
      <p><strong>Published on: </strong><%= @book.publication_date %></p>
      <p><strong>Language: </strong> <%= @book.language %></p>

      <h5 class="mt-4">Description:</h5>
      <p class="text-muted"><%= @book.description %></p>
    </div>
  </div>

  <!-- Buttons -->
  <div class="d-flex justify-content-center mt-4">
    <%= link_to "Back", root_path, class: "btn btn-secondary me-3" %>

    <% if !user_signed_in? || (user_signed_in? && current_user.role == "customer") %>
      <%= link_to "Add to Bag", cart_item_add_path(book_id: @book.id), data: { turbo_method: "post" }, class: "btn btn-primary me-3" %>
    <% end %>

    <% if user_signed_in? && current_user.role == "author" %>
      <%= link_to "Edit", edit_book_path(@book), class: "btn btn-warning me-3" %>
      <%= link_to "Delete", book_path(@book), data: { turbo_method: "delete", turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %>
    <% end %>
  </div>

  <!-- Review Form -->
  <% if user_signed_in? && current_user.role == "customer" %>
    <div class="card my-5 shadow-sm">
      <div class="card-body">
        <h3 class="card-title">Leave a Review</h3>
        <%= form_with model: [@book, Feedback.new], local: true do |f| %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.hidden_field :book_id, value: @book.id %>

          <div class="mb-3">
            <%= f.label :rating, "Rating", class: "form-label" %>
            <%= f.number_field :rating, class: "form-control", min: 1, max: 5, required: true %>
          </div>

          <div class="mb-3">
            <%= f.label :comment, "Comment", class: "form-label" %>
            <%= f.text_area :comment, class: "form-control", rows: 3, required: true %>
          </div>

          <%= f.submit "Submit Feedback", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  <% end %>

  <!-- Reviews Section -->
  <% @book.feedbacks.each do |feedback| %>
    <div class="card my-4 shadow-sm">
      <div class="card-header fw-bold">
        <%= feedback.name %> <!-- Assuming feedback belongs to user -->
      </div>
      <div class="card-body">
        <h5 class="card-title">Rating: <%= feedback.rating %> ⭐</h5>
        <p class="card-text"><%= feedback.comment %></p>

        <% if user_signed_in? && feedback.current_user == current_user.id %>
          <div class="d-flex">
            <%= link_to "Edit", edit_book_feedback_path(feedback), class: "btn btn-sm btn-outline-primary me-2" %>
            <%= link_to "Delete", book_feedback_path(feedback), data: { turbo_method: "delete", turbo_confirm: "Are you sure?" }, class: "btn btn-sm btn-outline-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

</div>